name: Deploy with PM2

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Add environment variables
        env:
          DATABASE_URL: ${{ secrets.DB_URL }}
        run: 
          echo "DATABASE_URL=${{ secrets.DATABASE_URL }}" >> .env
          cat .env

      - name: Install dependencies
        run: npm install

      - name: Setup Prisma
        run: npx prisma generate

      - name: Build project
        run: NODE_OPTIONS="--max-old-space-size=4096" npm run build

      - name: Restart with PM2
        run: |
          if pm2 describe TestGithubActions > /dev/null; then
          pm2 delete TestGithubActions
          fi  
          pm2 start dist/main.js --name "TestGithubActions" # Adjust the entry point to your project's start file
          pm2 save # Save the PM2 process list